server:
  port: 9087
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/xcf6000e?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: whnr
    password: 123456
#    url: jdbc:mysql://172.22.1.91:3306/xcf6000e?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: sa
#    password: 250100
    initial-size: 10
    min-idle: 5
    max-active: 20
    max-wait: 30000
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates
    check-template-location: false
    check-template: false
  mvc:
    static-path-pattern: /static/**
logging:
  config: classpath:logback.xml
  level:
    org.example: debug

mysql.delDay: 1


swagger:
  enable: true


mybatis-plus:
  type-aliases-package: org.example.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
    cache-enabled: false #开启二级缓存
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-field: isDel
      logic-delete-value: 0